### ISSUE TITLE
Incorrect shebang in Ubuntu 20.04 + ROS Noetic

### ISSUE THREAD

**Issue by RafaelRey** [ros-visualization/rqt_service_caller#17]
Hello, 

I've been looking around the pull requests and issues opened. I saw that the python3 shebang compatibility was supposedly fixed, but I found using the 0.4.9-focal version of rqt_service_caller that the shebang of the rqt_service_caller installed script is still 

`#!/usr/bin/env python`

instead of

`#!/usr/bin/env python3`

I tried to reinstall the package but it does change nothing, At the moment replacing it manually does the job

Edit: Sorry for the edit, but I saw that the problem is just that the package has not been released since the fix was added to the CMakeLists

**Comment by mikaelarguedas** [comment]
Version 0.4.10 including the fix has been released. Can you confirm this issue is now solved ?

**Comment by RafaelRey** [comment]
Yes, the current release has the correct shebang, thank you very much!
