### ISSUE TITLE
ROS2: Calling a service that no longer exists hangs rqt_service_caller

### ISSUE THREAD

**Issue by brawner** [ros-visualization/rqt_service_caller#9]
When calling a service that is no longer offered by a server, the plugin will hang and not exit out of the while loop below.

https://github.com/ros-visualization/rqt_service_caller/blob/7dee1c4d9389b5a35df9b56a44ff030536ae179d/src/rqt_service_caller/service_caller_widget.py#L362-L367

**Comment by clalancette** [comment]
This was fixed years ago, so closing.
